const HertzCircular = HertzCircularContactForceGenerator
const HertzElliptical = HertzEllipticalContactForceGenerator
const BrickHalfSpacePenalty = BrickHalfSpacePenaltyContactForceGenerator
const ElasticFoundation = ElasticFoundationContactForceGenerator
const DoNothing = DoNothingContactForceGenerator
const ThrowError = ThrowErrorContactForceGenerator
